version: '2'

networks:
  think_network:
    external: true

services:
  thinkapigetway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ThinkAPIGetway
    networks:
      - think_network
    ports:
    - "80:80"

    restart: always

